name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Setup environment in order to build the Android app.
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.3'

    # Get flutter dependencies.
    - run: flutter pub get

    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .

    # Build apk.
    - run: flutter build apk
    - run: flutter build appbundle

    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"
        token: ${{ secrets.GITHUB_TOKEN }}
